name: Build Geode Mod
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [android32, android64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geode-sdk/build-geode-mod@v2
        id: build
        with:
          sdk: nightly
          target: ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: AutoPlayer-${{ matrix.target }}
          path: ${{ steps.build.outputs.build-output }}
