name: Build Geode Mod
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          sdk: nightly
          platform: android64
      - uses: actions/upload-artifact@v4
        with:
          name: AutoPlayer-android
          path: ${{ steps.build.outputs.build-output }}
